### ISSUE TITLE
is the plugin can be install by phonegap build 3.1

### ISSUE THREAD

**Issue by bau720123** [dawsonloudon/VideoPlayer#1]
is the plugin can be install by phonegap build 3.1

because of that the latest phonegap build version seem to be "3.1" (seem not ready 3.2+ version for now)

**Comment by bau720123** [comment]
I tried it
your plugin is not support phonegap build 3.1
just support by 3.2 or 3.3
close it，thanks

**Comment by dawsonloudon** [comment]
Sorry, I wasn't able to test in 3.1

**Comment by bau720123** [comment]
I am already upgrade to 3.3 version
thanks for your help~
