### ISSUE TITLE
network error trying to play video

### ISSUE THREAD

**Issue by sjvisschers** [dawsonloudon/VideoPlayer#10]
When I try to play a youtube video 
`VideoPlayer.play(https://www.youtube.com/watch?v=yny5MMjciGc)`

it opens the youtube app, but I get a network error.

It only happens on android, as far as I know. (Tested both on 2.3 & 4.3)

regards,
sjvisschers

**Comment by dawsonloudon** [comment]
Thank you for finding this. I will take a look into it over the weekend and get back to you with what I can find.

**Comment by sjvisschers** [comment]
Oops, I have made a mistake. While I was testing my app, I had changed the date & time of my device. It seems that this was creating the network error. So the plugin is working just fine for me now.

Thanks for your great work on this plugin.
