### ISSUE TITLE
is there any plan to develop in ios or winphone

### ISSUE THREAD

**Issue by bau720123** [dawsonloudon/VideoPlayer#2]
is there any plan to develop in ios or winphone
it is a good plugin that I use that~

**Comment by dawsonloudon** [comment]
Sorry for the long response time...

I don't plan on anything for iOS as it can handle the video natively. I am not familiar with how WP8 handles video, but I will look into it and add support if needed.

Thank you!

**Comment by bau720123** [comment]
OK
thanks you too

**Comment by dawsonloudon** [comment]
Closing this, will inform when I get to take a look at WP8
