### ISSUE TITLE
What is correct way to install it?

### ISSUE THREAD

**Issue by alxgrn** [dawsonloudon/VideoPlayer#3]
I apologize for maybe stupid question, but how to install this plugin?
Can you add instructions to README.md?

**Comment by dawsonloudon** [comment]
For the CLI:
cordova plugin add https://github.com/dawsonloudon/VideoPlayer.git

For PGBuild:
Add to config.xml

<gap:plugin name="com.dawsonloudon.videoplayer" version="1.0.0" />

**Comment by dawsonloudon** [comment]
And, yes I will update the README.md with this info. Thanks for the suggestion!

**Comment by dawsonloudon** [comment]
Have updated the README.md, closing
