### ISSUE TITLE
can't install it

### ISSUE THREAD

**Issue by masterofdaemon** [dawsonloudon/VideoPlayer#4]
can you give me test(example) fully working project (compile,run and watch video) ?

**Comment by dawsonloudon** [comment]
Are you using PhoneGap Build or building locally? I will be adding more detailed install info to the README.md soon.

**Comment by masterofdaemon** [comment]
I'm using phonegap build

**Comment by dawsonloudon** [comment]
I have added the installation instructions to README.md and will be posting a working example soon.

**Comment by mbenedict26** [comment]
I'd also love to see a working example. I've followed the instructions, but my video will not launch. Thanks for everything!

**Comment by dawsonloudon** [comment]
Sorry, I am in the middle of a move between states. Hoping to have an example in the next week or so.

**Comment by mbenedict26** [comment]
That would be great... Thanks

**Comment by Emilize** [comment]
Good Morning, 
(sorry for my approximative english, i'm a French)

I've the same problem, I don't arrive to use you plugin. 
I would like to see an example, if is possible ? 

Thanks,

**Comment by dawsonloudon** [comment]
All, I should have an example added to this project by the end of the weekend. Thank you for your comments and patience.

**Comment by Emilize** [comment]
Thanks for your answer, when I launch my projet on my console (Cordova run android), I have this line of error : 
[TypeError: Cannot set property 'com.dawsonloudon.videoplayer' of undefined]. 

I don't understand..

**Comment by mbenedict26** [comment]
I got this working like a charm a couple of weeks ago... I really appreciate Dawson Loudon and his work on this. I'm at work, but I'll post my implementation when I get home.

**Comment by coolwebs** [comment]
Hi there,

I have also tried using this plugin along with Simon McDonald and several branches of his that fit for Cordova 3.xx. Even tried with jaeger25 but I am still not feeling the Android 'love'.

I get no errors but the video file is not playing at all. I am using the following code:

a onclick="javascript:VideoPlayer.play('https://www.youtube.com/watch?v=f7TD3Z03l2I');" href="#">Please view the video</a

I can't get it to work for local files either. I would fully support a working example with files. I haven't done anything in eclipse (someone earlier made reference to a .java file) but just used HTML, JavaSCript and the CLI. Is there something I am missing here?

*NOTE: I have had to leave the brackets of the a tag as my comment kept getting published in proper HTML

**Comment by coolwebs** [comment]
Plugins aside, I got it working by following this stackoverflow post and used:

android.resource://com.coolwebs.me/raw/myVideoName (of course omitting the .mp4 extension).
This would not work in the emulator and was bugging me late night. Lo and behold I actually try it on a device today and it works. Hurrah

http://stackoverflow.com/questions/19007788/loading-video-failed-on-html5-phonegap/20660189?noredirect=1#comment33991200_20660189

**Comment by dawsonloudon** [comment]
Thank you for the input and the link to SO. This may open up a better solution to how this plugin works. I am still behind on getting a working example, sorry.

**Comment by Emilize** [comment]
hello coolwebs !! 

I've again the same problem, I don't arrive to integrate my video on android.
If I good understand, you have find a solution... But, I've yet try with your link. 

Can you explain me your solution or not ?? I'm beginner in Js... 

Thank's !

**Comment by coolwebs** [comment]
Hey @ Emilize. You don't need to concern yourself with JavaScript for this. If you are using PhoneGap/Cordova locally, you can actually use the HTML5 video tag:

```
           <video class="responsive" width="100%" height="545px" poster="../img/specimen-pages/caddisfly-poster.jpg" controls>
          <source src="android.resource://com.oest.freshwater/raw/caddisfly">
        Your device does not support the HTML5 Video.
          </video> 
```

You will need to create a folder called "raw" inside the "res" directory for your Android project (i.e. ./platforms/android/res) and move your video files into that location. Then you just put "android.resource://com.company.projectname/raw/videofile" as the src in the video tag. Please make sure you do not put the video extension on the reference path (i.e. ".mp4"). Also when you created the project with command line you would have created a reverse domain-style identifier, "com.company.projectname". Please refer to PhoneGap docs if you need more information.

**Comment by dawsonloudon** [comment]
@coolwebs Do you think this plugin is still needed after your new findings? I'm trying to find time to update, but if there is a better solution maybe it's time to put it to rest? Thanks for your input.

**Comment by coolwebs** [comment]
Hi @dawsonloudon. It may work for some other people but perhaps the solution I put up might be simpler for people to use. But as android often changes the goal posts it might be good to leave it where it is, just in case. Your solution might better suit some projects. One forseeable drawback of using the solution I suggest is that the poster image does not stay and when the video is paused, it shows a grey video icon - same for when the video is played again. The poster images is a one time show.

**Comment by Emilize** [comment]
Waaaa @coolwebs thanks very much !!! 
It's works...  Yet I had try many solutions. 
Thanks to, I can to finish my project ! 

Your explication is perfect ! Really !!! 

Have a good day !

**Comment by kasia00** [comment]
help please. I'm trying play a local video with plugin but nothing happened. i remove plugin and try android.resource://com.company.projectname/raw/videofile" but only what i see is a picture.. what should i do sorry for my english

**Comment by coolwebs** [comment]
@kasia00 - do you have your videos in the 'raw' folder? And if you have, do you - do not refer to the extension in your code. See my earlier comment.

**Comment by kasia00** [comment]
i solved this problem !! the video tag doesn`t work on Android 4.4.1

**Comment by handripangestiaji** [comment]
@kasia00 - how you solved it ? i had same problem, added videos in the 'raw' folder, but seems the video doesn't want to play. please help me.

**Comment by kasia00** [comment]
```
<video class="responsive" width="100%" height="545px" poster="" controls>
      <source src="android.resource://com.example.AppT/raw/myvideo">
    Your device does not support the HTML5 Video.
      </video>
```

**Comment by spartanatreyu** [comment]
@kasia00 - can you explain your solution at all? Just copy-pasting code there isn't helping at all. What android version is your solution working for? Do you have the plugin installed or not?

I've been attempting to play a local video but it doesn't seem to be working. Haven't installed the plugin, have my videos in the raw folder and I'm running android 4.4.2 on my test device. If I get any positive results i'll post them here.

**Comment by spartanatreyu** [comment]
So on android 4.4.2, I've tried every combination of android.resource, file:///, cdvfile:// with placing the videos inside the app's www folder and res/raw folder and none worked. The plugin itself did work however.

Interestingly, the app could find some of the paths (as noted in the network tab when used with usb debugging) but when setting the the video element's source, the element is always stuck on 1:40 duration (regardless of if the file is a video or not) and couldn't play. Extending this further with the file plugin and file api, the app could find any files in a few different locations but would always be stuck on 1:40 duration and refuse to play them. I tried varying this up with reading files as blobs then generating blob urls to set as the video element's source and reading as files as arraybuffers which are placed into blobs then generating the bloburls to set as the element's source but they never worked.

I've decided in my app the best way to move forwards is to create a custom video element i can drop into my app's pages (in the angular framework, this is achieved with a custom directive).

For ios, this element will: 
create a new video element and attach to the DOM -> create a source attribute with a relative link to video file -> then play

... and for android:
create an img element with a relative link to the video's posterframe image -> add a touch event listener that will kick off the video plugin

**Comment by linkito87** [comment]
@spartanatreyu can you upload the code that u used in angular to do that?... I have the same problem... I have a video background for my app, and in iOS works fine, but in Android I can't view the video :(.

Please can u help me? Thanks

**Comment by spartanatreyu** [comment]
@linkito My video code is a little over the place but I put a gist here for you:

https://gist.github.com/spartanatreyu/dd7bc772a5ed85ff512a

**Comment by NereaElorza** [comment]
Hello
I cant install this plugin like in README.md you indicate. I have this error: 
Error: Failed to fetch plugin https://github.com/dawsonloudon/VideoPlayer.git via registry.
Do you know why it could be? thanks

**Comment by spartanatreyu** [comment]
@NereaElorza This repo hasn't been updated in 4 years. Probably not the video player you want to use considering how much android, cordova and the android platform code for cordova have changed.

**Comment by christianraj** [comment]
Can anyone help me to solve this issue

cordova plugin add https://github.com/dawsonloudon/VideoPlayer.git
(node:7264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin https://github.com/dawsonloudon/VideoPlayer.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: git+https://github.com/dawsonloudon/VideoPlayer.git.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2018-01-10T05_07_04_353Z-debug.log
(node:7264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by spartanatreyu** [comment]
@christianraj This plugin is super old now, it's not going to work on cordova anymore.

**Comment by coolwebs** [comment]
Hey everyone, you should really look at this repo to solve your issue - https://github.com/jaeger25/Html5Video/blob/master/README.md as it looks more actively maintained. It works on a similar method to bypass the local chrome browser restrictions on video files (`android.resource://`). If that does not work, I'd recommend investigating Crosswalk (https://crosswalk-project.org/documentation/cordova.html)
